### ISSUE TITLE
make: esptool2: Command not found

### ISSUE THREAD

**Issue by alexborisov** [slaff/esp8266.dev.box#13]
I'm trying to build the _esp8266/Basic_Blink_ example but I'm getting the following error:

```
# Generating image...
make: esptool2: Command not found
make: *** [out/build/app.out] Error 127
```

I'm running a fresh vagrant provisioned with _Sming_ as per the project wiki and [this article](https://blog.attachix.com/sming-for-esp8266-programming-for-esp8266-part-3/)

I've patched my `provision.sh` file to pull in esptools2 as per issue #12 

```
cd ~/dev
if [ ! -e ~/dev/raburton-esp8266 ]; then
  git clone https://github.com/raburton/esp8266 raburton-esp8266
fi

if [ ! -e ~/dev/raburton-esp8266/esptool2 ]; then
  cd ~/dev/raburton-esp8266
  git clone https://github.com/raburton/esptool2.git
  git clone https://github.com/raburton/rboot
fi

cd ~/dev/raburton-esp8266/esptool2
export XTENSA_BINDIR=$XTENSA_TOOLS_ROOT
make 
```

So I'm assuming there is something wrong with the environment variables. I've updated them manually in _Makefile-user.mk_:

```
ESP_HOME = /opt/Espressif
SMING_HOME = /home/vagrant/dev/Sming/Sming
```

But i'm guessing something is off - seeing that I was pulling esptool2 into _~/dev/raburton-esp8266/_

Any suggestions?

**Comment by slaff** [comment]
@alexborisov Most probably the executable binary is not in the PATH. I will check this.

**Comment by slaff** [comment]
@alexborisov Can you get the latest git version and try again?

**Comment by alexborisov** [comment]
```
# Generating image...
Generate firmware images successully in folder out/firmware.
Done
```

Awesome thanks. I hard reset everything and pulled the latest version. It looks like you fixed issue #12 as well :+1:

**Comment by rajatksud** [comment]
i cloned the develop version and find that issue is there. the esptool2 path in the Makefile-project.mk shows 
'# esptool2 path
ESPTOOL2 ?= esptool2 
should this not be 
ESPTOOL2 ?= $(ESP_HOME)/esptool2/esptool2
i hardcoded it to my path for the esp_home and it worked

**Comment by slaff** [comment]
The line `ESPTOOL2 ?= esptool2`  in your Makefile-project.mk file means check if the ESPTOOL env variable is set and if yes use it otherwise  use `esptool2` as value.

The `project/sming/provision.sh` script should have set already the correct env variable.

```
HAS_ESPTOOL2=`cat $PROFILE_CONF | grep ESPTOOL2 || :`
if [ -z "$HAS_ESPTOOL2" ]; then
  sudo echo "export ESPTOOL2=`pwd`/esptool2" >>  $PROFILE_CONF
  source $PROFILE_CONF
fi 
```

My suggestion would be to run again the Sming provisioning. This means that from the host machine you should run again

```
PROJECT=sming vagrant provision
```

Then check inside of the guest machine, the one that Vagrant created, if inside of the /etc/profile.d/ directory there is an esp8266.sh profile file and if it contains line starting with `export ESPTOOL2=`

**Comment by rajatksud** [comment]
i am using vagrant on a windows machine and i cant seem to provision the projects. 
vagrant provision keeps rebuilding the Espressif Home. I use cmder for this, although it does state project = sming but it does not update the Sming files. Thanks for the help. What you suggest seems correct.
