### ISSUE TITLE
Shared folders not mounted

### ISSUE THREAD

**Issue by ldeffenb** [slaff/esp8266.dev.box#16]
In a freshly constructed vagrant vm, the Shared Folders are not mounted.  I see them in the VirtualBox Manager, but there's nothing actually mounted.  Where should the following actually be mounted?

home_vagrant_dev - maybe ~/dev?
opt_provision_project - Got no clue
vagrant - maybe /vagrant?

**Comment by slaff** [comment]
On your local machine the  Espressif directory should be mounted as /opt/Espressif on the VM.
Espressif -> /opt/Espressif.
But this will happen ONLY if the local machine file system is case-sensitive. Which is not the case in Windows.

There are also other local directories that are mounted to the VM (no matter if the FS is case sensitive or not)

dev -> /home/vagrant/dev
project -> /opt/provision/project

That is defined in the [Vagrantfile](https://github.com/slaff/esp8266.dev.box/blob/master/Vagrantfile)
