### ISSUE TITLE
What is the password?

### ISSUE THREAD

**Issue by IanAber** [slaff/esp8266.dev.box#17]
I am trying to use this virtual machine in VMWare and I need to install the VMWare tools. I need to do this using sudo but the machine is requesting a password. What is the password for the esp8266 user?

**Comment by slaff** [comment]
The scripts here create a Virtualbox image with the help of Vagrant. And vagrant creates a standard user with name: `vagrant` and password `vagrant`. If you want to become root user as vagrant user you can use `sudo`.

**Comment by GitCatPixel** [comment]
Hello! First of all thanks for sharing your project! I must admit though that I have some troubles. When I try to get one of the available projects using the commands below (I am using Windows), the dev directory stays empty.
`
set PROJECT=sming
vagrant up
`

Could you tell me what I did wrong and how I can solve it?
