### ISSUE TITLE
Issues after the base image was upgraded

### ISSUE THREAD

**Issue by slaff** [slaff/esp8266.dev.box#2]
The old image “chef/ubuntu-14.04″ was replaced with a new one “bento/ubuntu-14.04″. One user is reporting that it is not working correctly (https://blog.attachix.com/programming-for-esp8266-part-1/#comment-15)

**Comment by itarozzi** [comment]
I switched to bento/ubuntu-14.04 and I had to add some packages to vm-bootstrap.sh file to compile the toolchain

```
 diff --git a/vm-bootstrap.sh b/vm-bootstrap.sh
 index 90a7d41..3b823b9 100755
 --- a/vm-bootstrap.sh
 +++ b/vm-bootstrap.sh
 @@ -5,9 +5,10 @@ PROJECT="$1"
 SDK_VERSION="$2"

 # Prepare the machine
sudo apt-get update
-sudo apt-get -y install git autoconf build-essential \
-     gperf bison flex texinfo libtool libncurses5-dev \

sudo apt-get update
+sudo apt-get -y install git cpp gcc g++ autoconf build-essential \
+     gperf bison flex texinfo libtool libtool-bin libncurses5-dev \
      wget gawk libc6-dev-amd64 python-serial libexpat-dev unzip
 if [ ! -d /opt/Espressif ]; then
   sudo mkdir /opt/Espressif
```

**Comment by slaff** [comment]
I decided to move to official "ubuntu/trusty32" base box (see c620c0b3d0cb4eb543d510e28eb831f46b8424be). That should eliminate unpleasant "surprises" in the near future.
