### ISSUE TITLE
Latest kernel update on Ubuntu 14.04 breaks Python Serial 

### ISSUE THREAD

**Issue by slaff** [slaff/esp8266.dev.box#5]
It is not possible to read/write to the serial interface with python due to some issues with the latest kernel. See [this issue](https://github.com/pyserial/pyserial/issues/17) and [that](https://bugs.launchpad.net/ubuntu/+source/python2.7/+bug/1501240) for more information and updates.

**Comment by slaff** [comment]
If you having the issue above and you are using kernel 3.13.0-65 then you can upgrade now by doing the following:

``` bash
sudo echo "deb http://archive.ubuntu.com/ubuntu trusty-proposed main" >> /etc/apt/sources.list
sudo echo "deb-src http://archive.ubuntu.com/ubuntu trusty-proposed main" >> /etc/apt/sources.list
sudo apt-get update 
sudo apt-get install linux-headers-3.13.0-66-generic linux-image-3.13.0-66-generic
```

Or wait for some days for the new kernel to be part of the main stream release and just issue the following commands:

``` bash
sudo apt-get update 
sudo apt-get install linux-headers-3.13.0-66-generic linux-image-3.13.0-66-generic
```

**Comment by daald** [comment]
The new kernel fixes python-serial, but it breaks lxc:

```
lxc-start: conf.c: setup_pts: 1772 Permission denied - mount failed '/dev/pts/ptmx'->'/dev/ptmx'
```
